export const LOGIN = 'LOGIN'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const FETCH_COURSE_DATA = 'FETCH_COURSE_DATA';
export const SEND_PAYMENT_DATA = 'SEND_PAYMENT_DATA';
export const GET_LEARNER_DATA = 'GET_LEARNER_DATA';
export const SIGNUP = 'SIGNUP'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const LOGIN_START = 'LOGIN_START'

export const FETCH_COURSE_REQUEST = 'FETCH_COURSE_REQUEST'
export const FETCH_COURSE_SUCCESSFUL = "FETCH_COURSE_SUCCESFUL"
export const FETCH_COURSE_FAILURE = "FETCH_COURSE_SUCCESSFUL"
export const POST_OTP = 'POST_OTP';
